services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "4040:3030"
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - ./fuseki-data:/fuseki
    restart: always

  fair_er:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - fuseki
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always
    
  fuji:
    image: ghcr.io/pangaea-data-publisher/fuji:latest
    ports:
      - "1071:1071"
    environment:
      - ENABLE_CORS=true
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge
