services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "4040:3030"
    environment:
      ADMIN_PASSWORD: ${FUSEKI_PASSWORD}
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - ./fuseki-data:/fuseki

  fair_er:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - fuseki
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
